language: ruby

rvm:
  - 1.9.3
  - 2.0.0

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test_with_coveralls
before_script:
  - psql -c 'create database garage_test;' -U postgres
