development:
  adapter: postgresql
  database: garage_development
  host: localhost
  port: 5432
  username: postgres
  password: 
  encoding: utf8

test: &test
  adapter: postgresql
  database: garage_test
  host: localhost
  port: 5432
  username: postgres
  password: 
  encoding: utf8
  min_messages: WARNING

production:
  adapter: postgresql
  database: garage_production
  host: localhost
  port: 5432
  username: postgres
  password: 
  encoding: utf8

cucumber:
  <<: *test
